name: melf
version: '0.1'
synopsis: An Elf parser
description: Parser for ELF object format
category: Data
author: Aleksey Makarov
maintainer: aleksey.makarov@gmail.com
copyright: Aleksey Makarov
license: BSD3
homepage: https://github.com/aleksey-makarov/melf
dependencies:
  - base >=4.6 && <5.0
tested-with: GHC == 8.10.2
ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wno-redundant-constraints

github: aleksey-makarov/melf

library:
  dependencies:
    - base >= 2 && < 5
    - bytestring
    - binary
    - exceptions
    - lens
    - prettyprinter
    - singletons
    - template-haskell
    - mtl
  source-dirs: src
  other-modules:
    - Data.Elf.Constants.TH
    - Data.Elf.Constants.Data
    - Data.Elf.Internal.Elf
    - Data.Interval
    - Data.BList
  exposed-modules:
    - Data.Endian
    - Data.Elf
    - Data.Elf.Constants
    - Data.Elf.Headers
    - Data.Elf.PrettyPrint
    - Control.Exception.ChainedException

tests:
  golden:
    main: Golden.hs
    source-dirs: tests
    dependencies:
      - base
      - binary
      - bytestring
      - directory
      - exceptions
      - filepath
      - melf
      - prettyprinter
      - singletons
      - tasty
      - tasty-golden
      - tasty-hunit
  exceptions:
    main: Exceptions.hs
    source-dirs: tests/exceptions
    dependencies:
      - base
      - exceptions
      - tasty
      - tasty-hunit
      - melf
  examples:
    main: Examples.hs
    source-dirs: examples
    dependencies:
      - base
      - bytestring
      - containers
      - exceptions
      - filepath
      - lens
      - melf
      - mtl
      - singletons
      - tasty
      - tasty-golden
      - tasty-hunit

executables:
  hobjdump:
    main: hObjDump.hs
    source-dirs: app
    ghc-options: -O2 -fno-warn-unused-do-bind -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - melf
      - binary
      - bytestring
      - optparse-applicative
      - prettyprinter
  hobjlayout:
    main: hObjLayout.hs
    source-dirs: app
    ghc-options: -O2 -fno-warn-unused-do-bind -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - melf
      - binary
      - prettyprinter
      - bytestring
      - exceptions
