name: melf
version: '1.2.0'
synopsis: An Elf parser
description: Parser for ELF object format
category: Data
author: Aleksey Makarov
maintainer: aleksey.makarov@gmail.com
copyright: Aleksey Makarov
license: BSD3
homepage: https://github.com/aleksey-makarov/melf
dependencies:
    - base >=4.13 && <5.0
tested-with: GHC == 8.8.4, GHC == 8.10.7, GHC == 9.0.2, GHC == 9.2.4, GHC == 9.2.5, GHC == 9.4.4
ghc-options: -Wall -Wcompat

extra-doc-files:
    - ChangeLog.md
    - README.md
    - examples/README_ru.md
data-files:
    - tests/testdata/orig/*.golden
    - examples/*.golden
    # Add only original tests to keep the size of the tarball small
    - testdata/orig/bloated
    - testdata/orig/tiny
    - testdata/orig/vdso

github: aleksey-makarov/melf

library:
  dependencies:
    - binary        >= 0.8.7 && < 0.9
    - bytestring    >= 0.10.10 && < 0.12
    - exceptions    >= 0.10.4 && < 0.11
    - lens          >= 5.0.1 && < 5.3
    - mtl           >= 2.2.2 && < 2.4
    - prettyprinter >= 1.7.0 && < 1.8
    - template-haskell >= 2.15 && < 2.21
  source-dirs: src
  other-modules:
    - Data.Elf.Constants.TH
    - Data.Elf.Constants.Data
    - Data.Internal.Elf
    - Data.Interval
    - Data.BList
  exposed-modules:
    - Data.Endian
    - Data.Elf
    - Data.Elf.Constants
    - Data.Elf.Headers
    - Data.Elf.PrettyPrint
    - Control.Exception.ChainedException

tests:
  golden:
    main: Golden.hs
    source-dirs: tests
    dependencies:
      - binary
      - bytestring
      - directory >= 1.3.6 && < 1.4
      - exceptions
      - filepath >= 1.4.2.1 && < 1.5
      - melf
      - prettyprinter
      - tasty >= 1.4.1 && < 1.5
      - tasty-golden >= 2.3.4 && < 2.4
      - tasty-hunit >= 0.10.0.3 && < 0.11
  exceptions:
    main: Exceptions.hs
    source-dirs: tests/exceptions
    dependencies:
      - exceptions
      - tasty
      - tasty-hunit
      - melf
  examples:
    main: Examples.hs
    source-dirs: examples
    dependencies:
      - bytestring
      - exceptions
      - filepath
      - melf
      - mtl
      - tasty
      - tasty-golden
      - tasty-hunit

executables:
  hobjdump:
    main: hObjDump.hs
    source-dirs: app
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - melf
      - binary
      - bytestring
      - optparse-applicative >= 0.16.1 && < 0.18
      - prettyprinter
  hobjlayout:
    main: hObjLayout.hs
    source-dirs: app
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - melf
      - binary
      - prettyprinter
      - bytestring
      - exceptions
