name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        lfs: true
    - uses: cachix/install-nix-action@v19
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: aleksey-makarov
        # If you chose signing key for write access
        # signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    # TODO: use cache with all the derivations

    - run: nix-build --argstr compilerVersion ghc88
    - run: nix-shell --argstr compilerVersion ghc88  --run "ghc --version"

    - run: nix-build --argstr compilerVersion ghc810
    - run: nix-shell --argstr compilerVersion ghc810 --run "ghc --version"

    - run: nix-build --argstr compilerVersion ghc90
    - run: nix-shell --argstr compilerVersion ghc90 --run "ghc --version"

    - run: nix-build --argstr compilerVersion ghc92
    - run: nix-shell --argstr compilerVersion ghc92  --run "ghc --version"

    - run: nix-build --argstr compilerVersion ghc94
    - run: nix-shell --argstr compilerVersion ghc94 --run "ghc --version"

    # - run: nix-build --argstr compilerVersion ghc96
    # - run: nix-shell --argstr compilerVersion ghc96  --run "ghc --version"
