name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        lfs: true
    - uses: cachix/install-nix-action@v19
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: aleksey-makarov
        # If you chose signing key for write access
        # signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    # TODO: use cache with all the derivations

    - run: nix-build --argstr compilerVersion ghc884
    - run: nix-shell --argstr compilerVersion ghc884  --run "ghc --version"

    - run: nix-build --argstr compilerVersion ghc8107
    - run: nix-shell --argstr compilerVersion ghc8107 --run "ghc --version"

    - run: nix-build --argstr compilerVersion ghc902
    - run: nix-shell --argstr compilerVersion ghc902 --run "ghc --version"

    - run: nix-build --argstr compilerVersion ghc924
    - run: nix-shell --argstr compilerVersion ghc924  --run "ghc --version"

    - run: nix-build --argstr compilerVersion ghc925
    - run: nix-shell --argstr compilerVersion ghc925 --run "ghc --version"

    - run: nix-build --argstr compilerVersion ghc944
    - run: nix-shell --argstr compilerVersion ghc944  --run "ghc --version"
